spring.application.name=book-online
spring.datasource.url=jdbc:postgresql://localhost:5432/Book-online
spring.datasource.username=book
spring.datasource.password=book
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

//54c16689bcd5a9b80663780e8c9d3c2a6dbbe6adabbf543541c2acdfdffc10dc